### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by wcorn** [wcorn/toy-project#1]
## 상세 내용
- 기초 프로젝트 설정 구현 및 세팅
## to-do
- [x] response 세팅
- [x] exception 세팅
- [x] rest docs 세팅
- [x] commit template 세팅
- [x] code convention 세팅
- [x] mysql jpa 세팅
- [x] redis 세팅
